version: "3.9"
services:
  web:
    build:
      context: .
      dockerfile: docker/django/Dockerfile
    volumes:
      - .:/app
    working_dir: /app/spycat_be
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    env_file:
      - .env

networks:
  spycat-network:
    external: true